[tool.poetry]
name = "ying"
version = "0.0.0"
description = ""
license = "MIT"
authors = ["Yannick Fricke"]
readme = "README.md"

[tool.poetry.scripts]
ying = "ying:main"

[tool.poetry.dependencies]
python = "^3.12"
rich = "^13.7.1"
black = "^24.4.2"

[tool.poetry.group.test.dependencies]
pytest = "^8.0.0"
pytest-mock = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
